### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by mxq15** [publicstaticvo/DAPL#1]
作者你好：
    我在复现代码是发现数据集与以前用的格式有所不同，但打开数据集是乱码，你能帮忙重发一下吗？
期待你的回复。谢谢

**Comment by publicstaticvo** [comment]
数据集是用tokenizer处理之后的，加了\001和\002作为分隔符，直接跑代码可以跑通。dataset.py的注释里写了数据集的格式。

**Comment by mxq15** [comment]
第一幅图是我看到的数据集形式，第二幅图是复现的结果。这个代码是消融后的代码吗







鱼在哭泣
***@***.***







                       
Original Email
                       
                     

Sender:"publicstaticvo"< ***@***.*** &gt;;

Sent Time:2023/3/27 23:38

To:"publicstaticvo/DAPL"< ***@***.*** &gt;;

Cc recipient:"mxq15"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [publicstaticvo/DAPL] 数据集 (Issue #1)




 
数据集是用tokenizer处理之后的，加了\001和\002作为分隔符，直接跑代码可以跑通。dataset.py的注释里写了数据集的格式。
 
&mdash;
